//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotCommander.ResX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotCommander.ResX.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámý výrobce.
        /// </summary>
        internal static string ExternalDevices_Manufacturer {
            get {
                return ResourceManager.GetString("ExternalDevices_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámý port.
        /// </summary>
        internal static string ExternalDevices_NoCom {
            get {
                return ResourceManager.GetString("ExternalDevices_NoCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámé ID.
        /// </summary>
        internal static string ExternalDevices_NoID {
            get {
                return ResourceManager.GetString("ExternalDevices_NoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámý název.
        /// </summary>
        internal static string ExternalDevices_NoName {
            get {
                return ResourceManager.GetString("ExternalDevices_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading fpv....
        /// </summary>
        internal static string FPV_LoadingCam {
            get {
                return ResourceManager.GetString("FPV_LoadingCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video....
        /// </summary>
        internal static string FPV_NoVideo {
            get {
                return ResourceManager.GetString("FPV_NoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with cam....
        /// </summary>
        internal static string FPV_ProblemWithCam {
            get {
                return ResourceManager.GetString("FPV_ProblemWithCam", resourceCulture);
            }
        }
    }
}
